# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerStats',
            new_name='activehosts',
        ),
    ]
